// client/src/actions/actionTypes.js

export default {
  NEWS_RECEIVED: 'NEWS_RECEIVED',
  NEWSITEM_RECEIVED: 'NEWSITEM_RECEIVED',
  NOTES_RECEIVED: 'NOTES_RECEIVED',
  NOTESITEM_RECEIVED: 'NOTESITEM_RECEIVED',
  MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
  MESSAGESITEM_RECEIVED: 'MESSAGESITEM_RECEIVED'
}
